version: 2.1
executors:
  worker:
    docker:
      - image: fr3akyphantom/droid-builder:latest
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
jobs:
  build:
    executor: worker
    environment:
      MANIFEST_BRANCH: 'android-10.0'
      VENDOR: 'xiaomi'
      CODENAME: 'dandelion'
      FLAVOR: 'eng'
      TEST_BUILD: 'true'
      MAINTAINER: 'PBRP Team'
      CHANGELOG: |
        - Test
    working_directory: /home/builder/pitchblack
    steps:
      - run:
          name: AIO Build
          command: |
            wget -q https://raw.githubusercontent.com/PitchBlackRecoveryProject/vendor_utils/pb/build.sh
            source build.sh
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: 'test'
          context: org-global
